# Generated by Django 4.1 on 2024-06-08 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('urls', models.JSONField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('links', models.JSONField()),
                ('files', models.JSONField()),
                ('keywords', models.JSONField()),
                ('date_crawled', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date crawled')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='api.school')),
            ],
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['date_added'], name='api_school_date_ad_9264ae_idx'),
        ),
    ]
