# Generated by Django 4.1 on 2024-06-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooldata',
            name='contents',
        ),
        migrations.AddField(
            model_name='school',
            name='contents',
            field=models.TextField(default=''),
        ),
    ]
