# Generated by Django 4.1 on 2024-06-11 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_schooldata_contents_school_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=200)),
                ('school_link', models.CharField(max_length=200)),
                ('date_suggested', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date suggested')),
            ],
        ),
    ]
