# Generated by Django 4.1 on 2024-06-11 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_suggestedschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('error', models.TextField()),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date reported')),
            ],
        ),
    ]
