name: Django Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: myenv
        environment-file: environment.yml

    - name: Install additional dependencies
      run: |
        conda run -n myenv pip install -r requirements.txt

    - name: Apply migrations
      run: |
        cd backend
        conda run -n myenv python manage.py migrate

    - name: Run Django server
      run: |
        cd backend
        conda run -n myenv python manage.py runserver
      env:
        DJANGO_SETTINGS_MODULE: myproject.settings
